db.rest.find().pretty()
db.rest.find({}, {restaurant_id:1, name:1, borough:1, cuisine:1})
db.rest.find({}, {restaurant_id:1, name:1, borough:1, cuisine:1, _id:0})
db.rest.find({}, {restaurant_id:1, name:1, borough:1, 'address.zipcode':1, _id:0})
db.rest.find({borough:'Bronx'})
db.rest.find({borough:'Bronx'}).limit(5)
db.rest.find({borough:'Bronx'}).skip(5).limit(5)
db.rest.find({'grades.score':{$gt: 90}})
db.rest.find({'grades.score':{$gt: 80, $lt: 100}})
db.rest.find({'address.coord.0': {$lt: -95.754168}})
db.rest.find({cuisine: {$ne: 'American'}, 'grades.score': {$gt: 70}, 'address.coord.0': {$lt: -65.754168}})
db.rest.find({cuisine: {$ne: 'American'}, 'grades.score': {$gt: 70}, 'address.coord.0': {$lt: -65.754168}})
db.rest.find({cuisine: {$ne: 'American'}, borough: {$ne: 'Brooklyn'}, 'grades.grade': 'A'}).sort({cuisine: -1})
db.rest.find({name: {$regex: '^Wil'}}, {restaurant_id:1, name:1, borough:1, cuisine:1, _id: 0})
db.rest.find({name: {$regex: 'ces$'}}, {restaurant_id:1, name:1, borough:1, cuisine:1, _id: 0})
db.rest.find({name: {$regex: 'Reg'}}, {restaurant_id:1, name:1, borough:1, cuisine:1, _id: 0})
db.rest.find({borough: 'Bronx', cuisine: { $in: ['American', 'Chinese']}})
db.rest.find({borough: {$in: ['Staten Island', 'Queens', 'Bronx', 'Brooklyn']}}, {restaurant_id:1, name:1, borough:1, cuisine:1, _id: 0})
db.rest.find({borough: {$nin: ['Staten Island', 'Queens', 'Bronx', 'Brooklyn']}}, {restaurant_id:1, name:1, borough:1, cuisine:1, _id: 0})
db.rest.find({'grades.score': {$lt: 10}}, {restaurant_id:1, name:1, borough:1, cuisine:1, _id: 0})
db.rest.find({$or: [{$and: [{cuisine: 'Fish'}, {cuisine: {$nin: ['American', 'Chinese']}}]},{name: {$regex: '^Wil'}}]},{restaurant_id:1, name:1, borough:1, cuisine:1, _id: 0})
db.rest.find({grades: {$elemMatch: {grade: 'A',score: 11,date: ISODate("2014-08-11T00:00:00Z")}}},{restaurant_id:1, name:1, grades:1, _id: 0})
db.rest.find({"grades.1.grade": "A","grades.1.score": 9,"grades.1.date": ISODate("2014-08-11T00:00:00Z")},{restaurant_id: 1, name: 1, grades: 1, _id: 0})
db.rest.find({"address.coord.1": { $gt: 42, $lt: 52 }},{restaurant_id: 1, name: 1, address: 1, _id: 0})
db.rest.find({}).sort({name:1})
db.rest.find({}).sort({name:-1})
db.rest.find({}).sort({cuisine:1, borought:-1})
db.rest.find({'address.street': null})
db.rest.find({'address.coord': {$type: 1}})
db.rest.aggregate([{$unwind: "$grades" }, {$match: {$expr: {$eq: [{ $mod: ["$grades.score", 7] },0]}}},{$project: {restaurant_id: 1,name: 1,'grades.grade': 1,_id: 0}}])
db.rest.find({name: {$regex: 'mon'}},{name: 1, borough: 1, 'address.coord': 1, cuisine: 1, _id: 0})
db.rest.find({name: {$regex: '^Mad'}},{name: 1, borough: 1, 'address.coord': 1, cuisine: 1, _id: 0})
